### ISSUE TITLE
Has this project been abandoned?

### ISSUE THREAD

**Issue by saransh323** [sujaykonda/MoneyMakingMaker#1]
I was casually looking for an flipping tools, and I found this one. Is it abandoned or unfinished? I can’t seem to find a way to work it. Do I just download the repo and run “python main.py”?

**Comment by sujaykonda** [comment]
it is a discord bot so to use it you must join the discord server: https://discord.gg/DYcPtcTc4T

**Comment by Saransh323** [comment]
Oh, ok, ty

**Comment by saransh323** [comment]
Discord says that the link is invalid tho...

**Comment by sujaykonda** [comment]
it should be fixed now

**Comment by saransh323** [comment]
Ty!
